fix: remove unnecessary configuration from tsconfig
boxfish-studio/sveltekit-cookie-manager pull request #130
Opened 2023-05-22 13:51 UTC by VmMad

Fixes #129

2023-05-25 15:28 UTC, evavirseda commented on svelte.config.js
> +		alias: {
`alias` are already included in `vite.config.js` :mag:

2023-05-29 15:59 UTC, evavirseda approved these changes
LGTM :star:

2023-05-30 08:43 UTC, begonaalvarezd requested changes
devmode is broken in this PR

2023-05-30 08:51 UTC, begonaalvarezd approved these changes
mea culpa

2023-05-30 08:51 UTC, merged