feat: configure linter and add it to the precommit staged hook
boxfish-studio/sveltekit-cookie-manager pull request #99
Opened 2023-01-09 13:10 UTC by evavirseda

Closes #92

2023-01-12 09:48 UTC, VmMad requested changes

2023-01-12 09:48 UTC, VmMad commented on package.json
> +	},
i dont think the precommit is working as it should

2023-01-12 10:33 UTC, VmMad approved these changes
Works fine!

2023-01-23 12:40 UTC, begonaalvarezd approved these changes

2023-01-23 12:46 UTC, begonaalvarezd approved these changes

2023-01-23 12:46 UTC, merged